### ISSUE TITLE
Ajout d'un système de mailing pour la confirmation et la réinitialisation de mot de passe

### ISSUE THREAD

**Issue by RedsTom** [Developpons-Discord/ReviewerApi#1]
# Général
- [x] Trouver un serveur mail
- [x] Ajouter les libraries nécessaires à l'envoi de mail et les configurer
# Confirmation de l'email
- [x] Créer le template
- [x] Créer le système de vérification
- [x] Implémenter la vérification côté frontend
# Réinitialisation du mot de passe
- [x] Créer le template
- [x] Créer les systèmes nécessaires derrière
- [x] Implémenter le frontend

**Comment by Welpike** [comment]
change password feature API part was merged, and the front end part will be merged today or tomorrow (i hope ^^')
